### ISSUE TITLE
Binder doesn't work

### ISSUE THREAD

**Issue by rabernat** [LuddaLudwig/rces_final_project#1]
I'm slowly reviewing the final projects. Great work! I'd love to feature your project in our gallery.

Unfortunately, your binder doesn't work because you have not included an `environment.yml` file. You should review the instructions in https://earth-env-data-science.github.io/lectures/environment/binder.html

Based on your notebook, it looks like you `environment.yml` file will need something like this
```yaml
channels:
  - conda-forge
dependencies:
  - pandas
  - numpy
  - matplotlib
  - sklearn
  - gdal
  - osr
  - PIL
  - rasterio as rio
  - cartopy
  - xarray
```
but this is just a guess.

Try running your binder and seeing if it works, then you can close this issue.
